name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: make build

    - name: Get Version
      id: version
      uses: ashley-taylor/read-json-property-action@v1.0
      with:
        path: package.json
        property: version

    - name: Update Version
      run: make update_version VERSION=${{steps.version.outputs.value}}
    
    - name: Archive
      run: make archive

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: v${{steps.version.outputs.value}}
        release_name: v${{steps.version.outputs.value}}
        draft: true
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{steps.create_release.outputs.upload_url}}
        asset_path: Hash.alfredworkflow
        asset_name: Hash.alfredworkflow
        asset_content_type: application/zip
